# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting new features 🎉
      labels:
        - new-feature
        - enhancement
    - title: Other Changes
      labels:
        - "*"
